FROM node:latest

WORKDIR /knowme-api

COPY package*.json /knowme-api/

RUN npm install 

COPY . .

RUN npm run db-generate

RUN npm run build

ENV PORT ${PORT}
ENV DATABASE_URL ${DATABASE_URL}
ENV TWITTER_API_KEY ${TWITTER_API_KEY}
ENV TWITTER_API_KEY_SECRET ${TWITTER_API_KEY_SECRET}
ENV TWITTER_API_BEARER_TOKEN ${TWITTER_API_BEARER_TOKEN}
ENV TWITTER_BASE_URL ${TWITTER_BASE_URL}
ENV TWITTER_USER_ID=${TWITTER_USER_ID}
ENV HASHNODE_PERSONAL_ACCESS_TOKEN ${HASHNODE_PERSONAL_ACCESS_TOKEN}
ENV HASHNODE_USERNAME ${HASHNODE_USERNAME}
ENV HASHNODE_BASE_URL ${HASHNODE_BASE_URL}
ENV OEMBED_BASE_URL ${OEMBED_BASE_URL}
ENV TWITTER_USERNAME ${TWITTER_USERNAME}
ENV JWT_SECRET_KEY ${JWT_SECRET_KEY}

EXPOSE 3000

CMD ["npm", "start"]