name: lint
on:
  push:
    branches-ignore:
      - "main"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: User Node.js LTS
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint
